[build]
  command = "npm run build"
  publish = "dist/client"

[dev]
  command = "npm run dev"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

# These are only used to set up the template, and are not used in the build
# If you want to update the real values, change them in the site UI or CLI
[template.environment]
SESSION_SECRET = "foobar"
PUBLIC_STORE_DOMAIN = https://ljudochbildhornan-test.myshopify.com
PUBLIC_STOREFRONT_API_TOKEN = cdace888085a69a0e275774976ae683c
PRIVATE_STOREFRONT_API_TOKEN = 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
PUBLIC_CHECKOUT_DOMAIN = https://ljudochbildhornan-test.myshopify.com
PUBLIC_CUSTOMER_ACCOUNT_API_CLIENT_ID = 7be1349fae6b8412e590797a507637b2
VITE_GOOGLE_MAPS_API_KEY = AIzaSyDZ-eral-4snpZMETDJD3kHKyqQS_u4DWM
